config/routes.rb
Rails.application.routes.draw do
  resources :pieces, not: [:edit, :update]
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piece.rb
class Piece < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @piece = Piece.new(piece_params)
    if @piece.save
      redirect_to pieces_path
    else
      puts "Not saved"
    end
  end

  def destroy
  end


  private

  def piece_params
    params.require(:piece).permit(:name, :id, :description, :url)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      puts "Not saved"
    end
  end

  def destroy
  end


  private

  def room_params
    params.require(:room).permit(:name, :width, :length, :height)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furnisure</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pieces/destroy.html.erb
<h1>Pieces#destroy</h1>
<p>Find me in app/views/pieces/destroy.html.erb</p>

app/views/pieces/index.html.erb
<h1>Pieces#index</h1>
<p>Find me in app/views/pieces/index.html.erb</p>

app/views/pieces/new.html.erb
<h1>Pieces#new</h1>
<p>Find me in app/views/pieces/new.html.erb</p>

app/views/pieces/show.html.erb
<h1>Pieces#show</h1>
<p>Find me in app/views/pieces/show.html.erb</p>

app/views/rooms/_room.html.erb
<div id="target-area1"
    class="target-area <%= @room.floor %>"
    style="position:relative; width:<%= @room.width * @room_multiplier %>px;
    height:<%= @room.length * @room_multiplier %>px;">
</div>

app/views/rooms/index.html.erb
<div class="container">
  <% @rooms.each do |room| %>
    <%= link_to room_path(room) do %>
    <div class="card w-25 p-1 mt-1">
      <p class="card-title mt-3"><%= room.name %></p>
    </div>
    <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="container pt-2">
  <h2><%= @room.name %></h2>

</div>

<div class="container new-page-identifier mt-0" id="new-song-container">
  <div class="row" >
    <div id="library-container">
      <div id="library">
        <% pieces = Piece.all.to_a %>
        <% pieces.each_with_index do  |piece, index| %>
          <div id="piece<%= index %>" class="lib-item">
            <% @library_multiplier = 0.4 %>
            <% @room_multiplier = 0.7 %>
            <h6 class='m-0' ><%= piece.name %></h6>
            <% myWidth = (piece.width * @library_multiplier).to_s  + "px" %>
            <% myHeight = (piece.depth * @library_multiplier).to_s + "px" %>
            <% width_in_room =  (piece.width * @room_multiplier) %>
            <% height_in_room =  (piece.depth * @room_multiplier) %>
            <div id="piece image <%= index %>" draggable="true"  class="draggable <%= piece.color.sub("$", "") %>" data-name="<%= piece.name %>" data-color="<%= piece.color %>"
              style='width: <%= myWidth %>; height: <%= myHeight %>; border-top: 2px solid rgba(30,30,30, 0.4); background-color: "${piece.color}";'
              data-roomwidth= <%= width_in_room %> data-roomheight=<%= height_in_room %>>
            </div>



            <% color_array = piece.available_colors.split(",") %>
            <select name="colors" id="colors" class="form-control color-select mt-1 p-1"> value=<%= piece.color %>
              <% color_array.each do | color | %>
              <% if (color.gsub(" ", "") === piece.color.gsub(" ", "")) %>
                <option selected ><%= color.sub("$", "").gsub(" ", "").gsub(/-/, " ").titleize %></option>
              <% else %>
                <option><%= color.sub("$", "").gsub(" ", "").gsub(/-/, " ").titleize %></option>
              <% end %>
              <% end %>
            </select>
          </div>
        <% end %>
      </div>
      <%= render partial: "room" %>
    </div>
    <%= image_tag  'arm_red.jpg', id:"big-image", class:'big-image' %>
      <!-- <img id="big-image" src="../../assets/images/arm_red.jpg" alt=""> -->
      </div>
    </div>
    </div>
  </div>
</div>